IwM_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aquarium.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

aquarium/urls.py
from django.urls import path
from .views import (
    FeedingListView,
    FeedingDetailView,
    FeedingCreateView,
    WaterchangeListView,
    WaterchangeDetailView,
    WaterchangeCreateView,
)
from . import views as aq_views

app_name = 'aquarium'
urlpatterns = [
    path('', aq_views.home, name='home'),

    path('feeding-log/', FeedingListView.as_view(), name='feeding-log'),
    path('feeding/<int:pk>/', FeedingDetailView.as_view(), name='feeding-detail'),
    path('feeding-log/new/', FeedingCreateView.as_view(), name='feeding-create'),

    path('waterchange-log/', WaterchangeListView.as_view(), name='waterchange-log'),
    path('waterchange/<int:pk>/', WaterchangeDetailView.as_view(), name='waterchange-detail'),
    path('waterchange-log/new/', WaterchangeCreateView.as_view(), name='waterchange-create'),

    path('increase/', aq_views.increase, name='increase'),
    path('decrease/', aq_views.decrease, name='increase'),

    path('lighton/', aq_views.lighton, name='lighton'),
    path('lightoff/', aq_views.lightoff, name='lightoff'),

    path('bulbulatoron/', aq_views.bulbulatoron, name='bulbulatoron'),
    path('bulbulatoroff/', aq_views.bulbulatoroff, name='bulbulatoroff'),


]

aquarium/models.py
from django.db import models
from django.contrib.auth.models import User


class Temperature(models.Model):
    temp = models.DecimalField(max_digits=3, decimal_places=1, default=10.0)

    def __str__(self):
        return str(self.temp)


class Light(models.Model):
    light_state = models.BooleanField(default=False)

    def __str__(self):
        return str(self.light_state)


class Bulbulator(models.Model):
    bulbulator_state = models.BooleanField(default=False)

    def __str__(self):
        return str(self.bulbulator_state)


class Feeding(models.Model):
    notif_title = 'Last fish feeding'
    date_fed = models.DateTimeField(auto_now=True)
    by_whom = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.notif_title


class Waterchange(models.Model):
    notif_title = 'Last time water was changed'
    date_waterchanged = models.DateTimeField(auto_now=True)
    by_whom = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.notif_title

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

aquarium/views.py
from django.shortcuts import render, redirect
from datetime import datetime
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import F
from .models import Temperature, Light, Bulbulator, Feeding, Waterchange



def home(request):
    context = {
        'title': 'Your Aquarium\'s Control Panel',
        'feedings': Feeding.objects.order_by('-date_fed')[:1],
        'water_changes': Waterchange.objects.order_by('-date_waterchanged')[:1],
        'date': datetime.now(),
        'temperature': Temperature.objects.get(pk=1),
        'light': Light.objects.get(pk=1),
        'bulbulator': Bulbulator.objects.get(pk=1),
    }

    return render(request, 'aquarium/home.html', context=context)


class FeedingListView(ListView):
    model = Feeding
    template_name = 'aquarium/feeding-log.html'
    context_object_name = 'feedings'
    ordering = ['-date_fed']
    paginate_by = 7


class FeedingDetailView(DetailView):
    model = Feeding


class FeedingCreateView(LoginRequiredMixin, CreateView):
    model = Feeding
    fields = '__all__'
    success_url = '/feeding-log/'

    def form_valid(self, form):
        form.instance.by_whom = self.request.user
        return super().form_valid(form)


class WaterchangeListView(ListView):
    model = Waterchange
    template_name = 'aquarium/waterchange-log.html'
    context_object_name = 'waterchanges'
    ordering = ['-date_waterchanged']
    paginate_by = 7


class WaterchangeDetailView(DetailView):
    model = Waterchange


class WaterchangeCreateView(LoginRequiredMixin, CreateView):
    model = Waterchange
    fields = '__all__'
    success_url = '/waterchange-log/'

    def form_valid(self, form):
        form.instance.by_whom = self.request.user
        return super().form_valid(form)


def feeding_log(request):
    context = {
        'title': 'Feeding Log',
    }
    return render(request, 'aquarium/feeding-log.html', context=context)


def increase(request):
    temp = Temperature.objects.update(temp=F('temp') + 1)
    return redirect('/')


def decrease(request):
    temp = Temperature.objects.update(temp=F('temp') - 1)
    return redirect('/')


def lighton(request):
    light_state = Light.objects.update(light_state=True)
    return redirect('/')


def lightoff(request):
    light_state = Light.objects.update(light_state=False)
    return redirect('/')


def bulbulatoron(request):
    bulbulator_state = Bulbulator.objects.update(bulbulator_state=True)
    return redirect('/')


def bulbulatoroff(request):
    bulbulator_state = Bulbulator.objects.update(bulbulator_state=False)
    return redirect('/')

users/views.py
from django.shortcuts import render, redirect
from .forms import UserRegisterForm
from django.contrib import messages


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"Account for {username} has been created! Log in now.")
            return redirect('login')
    else:
        form = UserRegisterForm()

    return render(request, 'users/register.html', context={'form': form})

aquarium/templates/aquarium/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        {% if title %}
            <title>{{ title }}</title>
        {% else %}
            <title>Your Aquarium's Control Panel</title>
        {% endif %}

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
              integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
              crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'aquarium/css/main.css' %}">
</head>
<body>
    <div id="wrap">
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel bg-gradient">
                <div class="container">
                    <a class="navbar-brand mr-4" href="{% url 'aquarium:home' %}">A<i style="font-size: 2ex"
                                                                                           class="fas fa-fish"></i>uarium</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                            aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarToggle">
                        <div class="navbar-nav mr-auto">
                            <a class="nav-item nav-link" href="{% url 'aquarium:feeding-log' %}">Feeding Log</a>
                            <a class="nav-item nav-link" href="{% url 'aquarium:waterchange-log' %}">Water Changing Log</a>
                        </div>
                        <!-- Navbar Right Side -->
                        <div class="navbar-nav">
                            {% if user.is_authenticated %}
                                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                            {% else %}
                                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </header>

        <div class="container">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}

            {% endblock content %}
    </div>
    </div>

    <div id="footer">
        <div class="container">
            <p class="text-muted credit"><span>Remote Aquarium Control Panel by Michał Barnaś</span></p>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
    <script src="{% static 'aquarium/js/temp_buttons.js' %}"></script>
    <script src="https://kit.fontawesome.com/a96ec5b2d1.js" crossorigin="anonymous"></script>

</body>
</html>

aquarium/templates/aquarium/feeding-log.html
{% extends 'aquarium/base.html' %}

{% block content %}
{% if user.is_authenticated %}
    <div class="center-box">
        <p class="date mt-5">{{ date|date:'l, H:i, j.n.Y' }}</p>
        <legend class="border-bottom mb-4">Aquarium remote feeding</legend>

                <button class="dynamic-button" type="submit" onclick="window.location.href='/feeding-log/new/';"> <i class="fas fa-shower"></i> Feed the fish now!
                    <i class="fas fa-shower"></i>
                </button>

            <div class="content_section">
                    <h4>{{ feeding.notif_title }}</h4>
                  {%  for feeding in feedings %}
                      <h1></h1>
                        <p2> The Fish were last fed by {{ feeding.by_whom }} on {{ feeding.date_fed|date:'l, H:i, j.n.Y'  }}</p2>
                  {% endfor %}
                  <hr class="mt-5">
                  {% if is_paginated %}
                      {% if page_obj.has_previous %}
                            <a class="dynamic-button " href="?page=1">First</a>
                            <a class="dynamic-button" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                      {% endif %}

                      {% for num in page_obj.paginator.page_range  %}
                            {% if page_obj.number == num %}
                                   <a class="dynamic-button" href="?page={{ num }}">{{ num }}</a>
                                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                                    <a class="dynamic-button " href="?page={{ num }}">{{ num }}</a>
                            {% endif %}
                      {% endfor %}

                            {% if page_obj.has_next %}
                                <a class="dynamic-button" href="?page={{ page.obj.next_page_number }}">Next</a>
                                <a class="dynamic-button " href="?page={{ page_obj.paginator.num_pages }}">Last</a>

                            {% endif %}

                      {% endif %}



            </div>



    </div>
{% else %}
    <div class="center-box">
        <h5 class="display-3 mt-5">This is your aquarium's control panel.</h5>
        <h5>Log in to make readings of parameters and control them</h5>
    </div>
{% endif %}
{% endblock content %}

aquarium/templates/aquarium/feeding_form.html
{% extends "aquarium/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <div>
        <form method="POST">
            {% csrf_token %}

            <fieldset class="form-group mt-3">
                <legend class="border-bottom mb-4">Aquarium remote feeding</legend>
                {{ form | crispy }}
            </fieldset>
            <div class="form-group">
                <button class="dynamic-button" type="submit">Feed the fish now!</button>
            </div>
        </form>
    </div>
{% endblock content %}

aquarium/templates/aquarium/home.html
{% extends 'aquarium/base.html' %}
{% load static %}

{% block content %}

    {% if user.is_authenticated %}
        <div class="center-box">
        <p class="date mt-5">{{ date|date:'l, H:i, j.n.Y' }}</p>
        </div>
        <hr class="mt-5">

            <div class="row">
                <div class="col-md">
                    <div class="content_section">
                          {%  for feeding in feedings %}
                                <h4>{{ feeding.notif_title }}</h4>
                                <p2> The Fish were last fed by {{ feeding.by_whom }} on {{ feeding.date_fed|date:'l, H:i, j.n.Y'  }}</p2>
                          {% endfor %}
                        <hr class="mt-5">
                        <button type="button" class="dynamic-button" onclick="window.location.href='/feeding-log/';">Go to details</button></a>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="content_section">
                        <h4 style="text-align: center">Watch aquarium's webcam live!</h4>
                        <div class="iframe-container">
                            <iframe src="https://www.youtube.com/embed/wNcwiMcbiWg?autoplay=1&rel=0&iv_load_policy=3&color=white" width="560" height="315" frameborder="0"></iframe>
                        </div>
                    </div>
                </div>


                <div class="col-md">
                    <div class="content_section">
                            {%  for water_change in  water_changes %}
                                <h4>{{ water_change.notif_title }}</h4>
                                <p2> The water in the tank was last changed by {{ water_change.by_whom }} on {{ water_change.date_waterchanged|date:'l, H:i, j.n.Y'  }}</p2>

                            {% endfor %}
                            <hr class="mt-5">
                            <button type="button" class="dynamic-button" onclick="window.location.href='/waterchange-log/';">Go to details</button></a>

                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <div class="content_section">
                            <div class="center-box">
                                <form method="POST" class="temp-buttons-form">
                                    <p >The aquarium light is now {% if  light.light_state == True %} On {% else %} Off {% endif %}</p>
                                    <button type="button" class="dynamic-button" onclick="window.location.href='/lighton/';">On</button>
                                    <button type="button" class="dynamic-button" onclick="window.location.href='/lightoff/';">Off</button>
                                </form>
                            </div>

                    </div>
                </div>

                <div class="col-md-4">
                    <div class="content_section">
                        <div class="center-box">
                            <p >Current water temperature is {{ temperature.temp }}<span>&#176;</span>C</p>
                            <div>
                                <form method="POST" class="temp-buttons-form">
                                    <button type="button" class="dynamic-button" onclick="window.location.href='/increase/';">
                                        <i class="fas fa-plus"></i>
                                    </button>
                                    <button type="button" class="dynamic-button ml-3" onclick="window.location.href='/decrease/';">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="content_section">
                        <div class="center-box">
                                <form method="POST" class="temp-buttons-form">
                                    <p >The bulbulator is {% if  bulbulator.bulbulator_state == True %} active {% else %} inactive {% endif %}</p>
                                    <button type="button" class="dynamic-button" onclick="window.location.href='/bulbulatoron/';">On</button>
                                    <button type="button" class="dynamic-button" onclick="window.location.href='/bulbulatoroff/';">Off</button>
                                </form>
                            </div>
                    </div>
                </div>
            </div>

    {% else %}
        <div class="center-box">
            <h5 class="display-3 mt-5">This is your aquarium's control panel.</h5>
            <h5>Log in to make readings of parameters and control them</h5>
        </div>
    {% endif %}

{% endblock content %}

aquarium/templates/aquarium/waterchange-log.html
{% extends 'aquarium/base.html' %}

{% block content %}
{% if user.is_authenticated %}
    <div class="center-box">
        <p class="date mt-5">{{ date|date:'l, H:i, j.n.Y' }}</p>
        <legend class="border-bottom mb-4">You changed aquarium's water recently? Share this info with other maintainers!</legend>

                <button class="dynamic-button" type="submit" onclick="window.location.href='/waterchange-log/new/';"> <i class="fas fa-water"></i> Change water now!
                    <i class="fas fa-water"></i>
                </button>

            <div class="content_section">
                    <h1>{{ waterchange.notif_title }}</h1>
                  {%  for waterchange in waterchanges %}
                            <h1></h1>
                        <p2> The water was last changed by {{ waterchange.by_whom }} on {{ waterchange.date_waterchanged|date:'l, H:i, j.n.Y'  }}</p2>
                  {% endfor %}


                  <hr class="mt-5">
                  {% if is_paginated %}
                      {% if page_obj.has_previous %}
                            <a class="dynamic-button " href="?page=1">First</a>
                            <a class="dynamic-button " href="?page={{ page_obj.previous_page_number }}">Previous</a>
                      {% endif %}

                      {% for num in page_obj.paginator.page_range  %}
                            {% if page_obj.number == num %}
                                   <a class="dynamic-button " href="?page={{ num }}">{{ num }}</a>
                                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                                    <a class="dynamic-button " href="?page={{ num }}">{{ num }}</a>
                            {% endif %}
                      {% endfor %}

                            {% if page_obj.has_next %}
                                <a class="dynamic-button " href="?page={{ page.obj.next_page_number }}">Next</a>
                                <a class="dynamic-button " href="?page={{ page_obj.paginator.num_pages }}">Last</a>

                            {% endif %}

                      {% endif %}



            </div>



    </div>
{% else %}
    <div class="center-box">
        <h5 class="display-3 mt-5">This is your aquarium's control panel.</h5>
        <h5>Log in to make readings of parameters and control them</h5>
    </div>
{% endif %}
{% endblock content %}

aquarium/templates/aquarium/waterchange_form.html
{% extends "aquarium/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <div>
        <form method="POST">
            {% csrf_token %}

            <fieldset class="form-group mt-3">
                <legend class="border-bottom mb-4">You changed aquarium's water recently? Share this info with other maintainers!</legend>
                {{ form | crispy }}
            </fieldset>
            <div class="form-group">
                <button class="dynamic-button" type="submit">Mark the water as changed</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/login.html
{% extends "aquarium/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <div>
        <form method="POST">
            {% csrf_token %}

            <fieldset class="form-group mt-3">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form | crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-light mt-3 mb-3" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">Need an account? <a class="ml-2 text-decoration-none" href="{% url 'register' %}">Sign Up Now</a></small>
        </div>
    </div>
{% endblock content %}

users/templates/users/logout.html
{% extends "aquarium/base.html" %}

{% block content %}
    <h2 class="mt-4">You have been logged out</h2>
    <h6><a href="{% url 'login' %}">Log in again</a></h6>
{% endblock content %}

users/templates/users/register.html
{% extends "aquarium/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <div>
        <form method="POST">
            {% csrf_token %}

            <fieldset class="form-group mt-3">
                <legend class="border-bottom mb-4">Registration</legend>
                {{ form | crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-light mt-3 mb-3" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">Already have an account? <a class="ml-2 text-decoration-none" href="{% url 'login' %}">Log In</a></small>
        </div>
    </div>
{% endblock content %}